codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "0...100"
  status:
    patch: off
    project:
      default:
        target: auto   # compares coverage to the previous base commit
        threshold: 1%  # allows variations around the target

comment: false
