.quartz_common:
    tags:
        - shell
        - quartz
    variables:
        PLAT: quartz
        MPIEXEC: srun
        MPIEXEC_NP: "-n"

#Precleanup

quartz_precleanup:
    extends: [.quartz_common, .precleanup]

# Setup

quartz_setup:
    extends: [.quartz_common, .setup]

#Build libs

quartz_build_hypre_gcc_6_1_0:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_hypre]

quartz_build_parmetis_gcc_6_1_0:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_metis]
    variables:
        METIS: parmetis

quartz_build_metis4_gcc_6_1_0:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_metis]
    variables:
        METIS: metis4

quartz_build_metis5_gcc_6_1_0:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_metis]
    variables:
        METIS: metis5
    allow_failure: true

# Build MFEM

quartz_build_mfem_gcc_4_9_3_debug_ser:
    extends: [.quartz_common, .with_gcc_4_9_3, .build_mfem]
    variables:
        MFEM_DEBUG: "YES"
        MFEM_USE_MPI: "NO"

quartz_build_mfem_gcc_6_1_0_debug_ser:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_mfem]
    variables:
        MFEM_DEBUG: "YES"
        MFEM_USE_MPI: "NO"

quartz_build_mfem_gcc_6_1_0_debug_par:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_mfem]
    variables:
        MFEM_DEBUG: "YES"
        MFEM_USE_MPI: "YES"
    needs: [quartz_build_hypre_gcc_6_1_0, quartz_build_parmetis_gcc_6_1_0]

quartz_build_mfem_gcc_6_1_0_opt_ser:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_mfem]
    variables:
        MFEM_DEBUG: "NO"
        MFEM_USE_MPI: "NO"

quartz_build_mfem_gcc_6_1_0_opt_par:
    extends: [.quartz_common, .with_gcc_6_1_0, .build_mfem]
    variables:
        MFEM_DEBUG: "NO"
        MFEM_USE_MPI: "YES"
    needs: [quartz_build_hypre_gcc_6_1_0, quartz_build_parmetis_gcc_6_1_0]

## Tests
# Code style check
quartz_stylecheck_mfem:
    extends: [.quartz_common, .stylecheck_mfem]

# Sanity check

quartz_sanitycheck_mfem_gcc_4_9_3_debug_ser:
    extends: [.quartz_common, .with_gcc_4_9_3, .sanitycheck_mfem]
    variables:
        MFEM_DEBUG: "YES"
        MFEM_USE_MPI: "NO"
    needs: [quartz_build_mfem_gcc_4_9_3_debug_ser]

quartz_sanitycheck_mfem_gcc_6_1_0_debug_ser:
    extends: [.quartz_common, .with_gcc_6_1_0, .sanitycheck_mfem]
    variables:
        MFEM_DEBUG: "YES"
        MFEM_USE_MPI: "NO"
    needs: [quartz_build_mfem_gcc_6_1_0_debug_ser]

quartz_sanitycheck_mfem_gcc_6_1_0_opt_ser:
    extends: [.quartz_common, .with_gcc_6_1_0, .sanitycheck_mfem]
    variables:
        MFEM_DEBUG: "NO"
        MFEM_USE_MPI: "NO"
    needs: [quartz_build_mfem_gcc_6_1_0_opt_ser]

quartz_sanitycheck_mfem_gcc_6_1_0_opt_par:
    extends: [.quartz_common, .with_gcc_6_1_0, .sanitycheck_mfem]
    variables:
        MFEM_DEBUG: "NO"
        MFEM_USE_MPI: "YES"
    needs: [quartz_build_mfem_gcc_6_1_0_opt_par]

# Postcleanup

quartz_postcleanup:
    extends: [.quartz_common, .postcleanup]
