# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: build-mfem

inputs:
  os:
    description: 'os'
    required: true
  debug:
    description: 'Debug status'
    required: false
    default: NO
  mpi:
    description: 'MPI status'
    required: false
    default: YES
  codecov:
    description: 'Codecov status'
    required: false
    default: NO
  hypre-dir:
    description: 'hypre install location working dir'
    required: true
  metis-dir:
    description: 'hypre install location working dir'
    required: true
  mfem-dir:
    description: 'mfem repo checkout location in working dir'
    required: true

runs:
  using: "composite"
  steps:
    - name: configure mfem
      run: |
        if [[ ${{ inputs.mpi }} == "YES" ]]
        then
          echo "Hypre symlink:"
          ln -s ${{ inputs.hypre-dir }} hypre;
          echo "Metis symlink:"
          ln -s ${{ inputs.metis-dir }} metis-4.0;
        fi
        CPPFLAGS="";
        if [[ ${{ inputs.os }} == 'ubuntu-latest' && ${{ inputs.debug }} == 'YES' ]]
        then
          CPPFLAGS+=" -pedantic -Wall -Werror";
        fi
        if [[ ${{ inputs.codecov }} == "YES" ]]
        then
          CPPFLAGS+=" --coverage -g";
        fi
        cd ${{ inputs.mfem-dir }};
        make config MFEM_USE_MPI=${{ inputs.mpi }} MFEM_MPI_NP=2 MFEM_DEBUG=${{ inputs.debug }} CPPFLAGS="$CPPFLAGS";
      shell: bash

    - name: make
      run: |
        cd ${{ inputs.mfem-dir }} && make all -j3
      shell: bash

