# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: checks-and-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_TOP_DIR: metis-4.0.3

# Note for future improvements:
#
# I cannot reuse cached dependencies and have to build them for each target although they could be shared sometimes. That's because Github cache Action has no read-only mode. But there is a PR ready for this (https://github.com/actions/cache/pull/489)

jobs:
  checks-and-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        debug: [YES, NO]
        mpi: [NO, YES]
        cmake: [NO]
        # 'include' allows to
        # - add a variable without creating a new matrix dimension.
        # - add a new combination ('cmake: YES' case here)
        #
        # note: we will gather coverage info for any non-debug run except the CMake build.
        include:
          - debug: YES
            codecov: NO
          - debug: NO
            codecov: YES
          - os: ubuntu-latest
            debug: NO
            codecov: NO
            mpi: YES
            cmake YES

    runs-on: ${{ matrix.os }}

    steps:
    # Checkout MFEM in "mfem" subdirectory. Final path: /home/runner/work/mfem/mfem/mfem
    # Note: it must be done now to access "install-hypre" and "install-metis" actions.
    - name: checkout mfem
      uses: actions/checkout@v2
      with:
        path: mfem
        # a fetch depth > 1 is required to retrieve the hash (dixit codecov)
        fetch-depth: 2

    # Only get MPI if defined for the job.
    # TODO (bernede1@llnl.gov): It would be nice to have only one step,
    # e.g. with a dedicated action, but I don’t see how at the moment.
    - name: get MPI (Linux)
      if: matrix.mpi == 'YES' && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install mpich libmpich-dev
        export MAKE_CXX_FLAG="MPICXX=mpic++"

    - name: get MPI (MacOS)
      if: matrix.mpi == 'YES' && matrix.os == 'macos-latest'
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew install openmpi
        export MAKE_CXX_FLAG="MPICXX=mpic++"

    # Get Hypre through cache, or install it.
    # Install will only run on cache miss.
    - name: cache hypre Install
      id: hypre-cache
      if: matrix.mpi == 'YES'
      uses: actions/cache@v2
      with:
        path: ${{ env.HYPRE_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.HYPRE_TOP_DIR }}-v1

    - name: get hypre
      if: matrix.mpi == 'YES' && steps.hypre-cache.outputs.cache-hit != 'true'
      uses: ./mfem/.github/actions/install-hypre
      with:
        hypre-archive: ${{ env.HYPRE_ARCHIVE }}
        hypre-dir: ${{ env.HYPRE_TOP_DIR }}

    # Get Metis through cache, or install it.
    # Install will only run on cache miss.
    - name: cache metis Install
      id: metis-cache
      if: matrix.mpi == 'YES'
      uses: actions/cache@v2
      with:
        path: ${{ env.METIS_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.METIS_TOP_DIR }}-v1

    - name: install metis
      if: matrix.mpi == 'YES' && steps.metis-cache.outputs.cache-hit != 'true'
      uses: ./mfem/.github/actions/install-metis
      with:
        metis-archive: ${{ env.METIS_ARCHIVE }}
        metis-dir: ${{ env.METIS_TOP_DIR }}

    # MFEM build and test
    - name: build
      uses: ./mfem/.github/actions/build-mfem
      with:
        os: ${{ matrix.os }}
        debug: ${{ matrix.debug }}
        codecov: ${{ matrix.codecov }}
        mpi: ${{ matrix.mpi }}
        cmake: ${{ matrix.cmake }}
        hypre-dir: ${{ env.HYPRE_TOP_DIR }}
        metis-dir: ${{ env.METIS_TOP_DIR }}
        mfem-dir: mfem

    # Run checks (and only checks) on debug targets
    - name: checks
      if: matrix.debug == 'YES'
      run: |
        cd mfem && make check
    - name: unit tests
      if: matrix.debug == 'NO'
      run: |
        cd mfem && make unittest
    - name: tests
      if: matrix.debug == 'NO'
      run: |
        cd mfem && make test

    - name: codecov
      uses: ./mfem/.github/actions/upload-coverage
      with:
        name: "os-${{ matrix.os }}-mpi-${{ matrix.mpi }}"
