# Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: "Sanitizers"

permissions:
  actions: write

on:
  push:
    branches:
      - master
      - next
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  # AddressSanitizer, UndefinedBehaviorSanitizer, and MemorySanitizer options
  MSAN_OPTIONS: "poison_in_dtor=1"
  UBSAN_OPTIONS: "halt_on_error=1, print_stacktrace=1"
  ASAN_OPTIONS: "detect_leaks=1,
                 strict_init_order=1,
                 strict_string_checks=1,
                 check_initialization_order=1,
                 detect_stack_use_after_return=1"
  LSAN_OPTIONS: "suppressions=${GITHUB_WORKSPACE}/asan.supp"
  # LLVM libcxx build options
  LLVM_INC: ${GITHUB_WORKSPACE}/llvm-build/include/c++/v1
  LLVM_LIB: ${GITHUB_WORKSPACE}/llvm-build/lib
  LLVM_VER: 18.1.3
  # Parallel MFEM build Hypre/Metis options
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_TOP_DIR: metis-4.0.3

jobs:
  Sanitizers:
    runs-on: ubuntu-latest
    strategy:
      # Avoid canceling all in-progress and queued jobs in the matrix if any one fails
      fail-fast: false
      matrix:
        sanitizer: [AddressSanitizer, UndefinedBehaviorSanitizer, MemorySanitizer]
        mpi: [seq, par]
        include:
          # AddressSanitizer
          # https://clang.llvm.org/docs/AddressSanitizer.html
          - sanitizer: AddressSanitizer
            cxxflags: "-fsanitize=address -fno-omit-frame-pointer
                       -fsanitize-address-use-after-scope"
            ldflags: "-fsanitize=address"
            llvm_sanitizer: "Address"

          # UndefinedBehaviorSanitizer
          # https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
          - sanitizer: UndefinedBehaviorSanitizer
            cxxflags: "-fsanitize=undefined -fno-omit-frame-pointer"
            ldflags: "-fsanitize=undefined"
            llvm_sanitizer: "Undefined"

          # MemorySanitizer
          # https://clang.llvm.org/docs/MemorySanitizer.html
          - sanitizer: MemorySanitizer
            cxxflags: "-fsanitize=memory -fno-omit-frame-pointer
                       -fsanitize-memory-track-origins -fsanitize-memory-use-after-dtor"
            ldflags: "-fsanitize=memory"
            llvm_sanitizer: "MemoryWithOrigins"

    name: "${{matrix.sanitizer}}-${{matrix.mpi}}"

    steps:

      ### MPI Setup
      ### https://manpages.ubuntu.com/manpages/jammy/man1/mpicxx.openmpi.1.html
      - name: Setup MPI
        if: matrix.mpi == 'par'
        run: |
          sudo apt-get install openmpi-bin libopenmpi-dev
          export OMPI_MCA_rmaps_base_oversubscribe=1
          echo "> mpicxx --version"
          mpicxx --version
          echo "> mpicxx --showme:compile"
          mpicxx --showme:compile
          echo "> mpicxx --showme:link"
          mpicxx --showme:link
          echo "> mpicxx --showme:command"
          mpicxx --showme:command
          echo "> mpicxx --showme:incdirs"
          mpicxx --showme:incdirs
          echo "> mpicxx --showme:libdirs"
          mpicxx --showme:libdirs
          echo "> mpicxx --showme:libs"
          mpicxx --showme:libs
          echo "> mpicxx --showme:version"
          mpicxx --showme:version
          
      # Create ASan suppression file
      - name: Create ASan suppression file
        working-directory: ${GITHUB_WORKSPACE}
        run: |
          cat > ${GITHUB_WORKSPACE}/asan.supp << EOF 
          leak:ompi_mpi_finalize
          leak:ompi_mpi_init
          leak:PMPI_Init
          leak:libevent_core-2.1.so
          leak:strdup
          EOF

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Setup Clang Environment
        run: |
          echo "CC=cc" >> $GITHUB_ENV
          echo "CXX=c++" >> $GITHUB_ENV
          echo "MPICXX=c++" >> $GITHUB_ENV

      - name: Showme MPI (Parallel)
        if: matrix.mpi == 'par'
        run: |
          echo "MPI_INC=$(mpicxx --showme:compile)" >> $GITHUB_ENV
          echo "MPI_LIB=$(mpicxx --showme:link)" >> $GITHUB_ENV

      - name: Setup LLVM Environment
        if: matrix.sanitizer != 'AddressSanitizer'
        run: |
          echo "LLVM_CXXFLAGS=-stdlib=libc++ -I${{env.LLVM_INC}} -Isystem${{env.LLVM_INC}}" >> $GITHUB_ENV
          echo "LLVM_LDFLAGS=-L${{env.LLVM_LIB}} -lc++abi -Wl,-rpath,${{env.LLVM_LIB}}" >> $GITHUB_ENV

      - name: Echo Environment
        run: |
          echo "[CC] ${{env.CC}} -v"
          ${{env.CC}} -v
          echo "[CXX] ${{env.CXX}} -v"
          ${{env.CXX}} -v
          echo "[MPICXX] ${{env.MPICXX}} -v"
          ${{env.MPICXX}} -v
          echo "[LLVM_CXXFLAGS] ${{env.LLVM_CXXFLAGS}}"
          echo "[LLVM_LDFLAGS] ${{env.LLVM_LDFLAGS}}"

      ### LLVM libcxx Build Steps
      - name: LLVM Cache
        if: matrix.sanitizer != 'AddressSanitizer'
        id: llvm-cache
        uses: actions/cache@v4
        with:
          path: ${GITHUB_WORKSPACE}/llvm-build
          key: ubuntu-latest-llvm-build-${{env.LLVM_VER}}-${{matrix.llvm_sanitizer}}

      - name: LLVM Clone
        if: matrix.sanitizer != 'AddressSanitizer' && steps.llvm-cache.outputs.cache-hit != 'true'
        run: >
          git clone --filter=blob:none --depth=1
          --branch llvmorg-${{env.LLVM_VER}}
          --no-checkout https://github.com/llvm/llvm-project.git llvm-project

      - name: LLVM Checkout
        if: matrix.sanitizer != 'AddressSanitizer' && steps.llvm-cache.outputs.cache-hit != 'true'
        working-directory: llvm-project
        run: |
          git sparse-checkout set --cone
          git checkout llvmorg-${{env.LLVM_VER}}
          git sparse-checkout set cmake llvm/cmake runtimes libcxx libcxxabi

      - name: LLVM Mkdir
        if: matrix.sanitizer != 'AddressSanitizer' && steps.llvm-cache.outputs.cache-hit != 'true'
        run: mkdir llvm-build

      - name: LLVM Configure
        if: matrix.sanitizer != 'AddressSanitizer' && steps.llvm-cache.outputs.cache-hit != 'true'
        working-directory: llvm-build
        run: >
          VERBOSE=1
          cmake -GNinja ../llvm-project/runtimes/
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DCMAKE_BUILD_TYPE=RelWithDebInfo
          -DCMAKE_INSTALL_PREFIX=/usr
          -DLLVM_USE_SANITIZER=${{matrix.llvm_sanitizer}}
          -DLLVM_BUILD_32_BITS=OFF
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF
          -DLLVM_INCLUDE_TESTS=OFF
          -DLIBCXX_INCLUDE_TESTS=OFF
          -DLIBCXX_INCLUDE_BENCHMARKS=OFF
          -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi'

      - name: LLVM CMake
        if: matrix.sanitizer != 'AddressSanitizer' && steps.llvm-cache.outputs.cache-hit != 'true'
        working-directory: llvm-build
        run: cmake --build . -- cxx cxxabi

      ### Cache restore Hypre, Metis
      ### https://github.com/actions/cache
      - name: HYPRE Cache
        id: hypre-cache
        if: matrix.mpi == 'par'
        uses: actions/cache@v4
        with:
          path: ${{env.HYPRE_TOP_DIR}}
          key: ubuntu-latest-ompi-build-${{env.HYPRE_TOP_DIR}}-int32-fp64-v2.5

      - name: HYPRE Build
        if: matrix.mpi == 'par' && steps.hypre-cache.outputs.cache-hit != 'true'
        uses: mfem/github-actions/build-hypre@v2.5
        with:
          archive: ${{env.HYPRE_ARCHIVE}}
          dir: ${{env.HYPRE_TOP_DIR}}
          target: int32
          precision: fp64
          build-system: make

      - name: METIS Cache
        id: metis-cache
        if: matrix.mpi == 'par'
        uses: actions/cache@v4
        with:
          path: ${{env.METIS_TOP_DIR}}
          key: ubuntu-latest-build-${{env.METIS_TOP_DIR}}-v2.5

      - name: METIS Build
        if: matrix.mpi == 'par' && steps.metis-cache.outputs.cache-hit != 'true'
        uses: mfem/github-actions/build-metis@v2.5
        with:
          archive: ${{env.METIS_ARCHIVE}}
          dir: ${{env.METIS_TOP_DIR}}

      ### MFEM Build and Test Steps
      - name: MFEM Checkout
        uses: actions/checkout@v4
        with:
          path: mfem

      - name: MFEM Build
        uses: mfem/github-actions/build-mfem@v2.5
        env:
          MPICXX: c++
          CXXFLAGS: "-g -O1 -std=c++17 ${{matrix.cxxflags}} ${{env.LLVM_CXXFLAGS}} ${{env.MPI_INC}} ${{env.MPI_LIB}} ${{env.LLVM_LDFLAGS}} -Wno-unused-command-line-argument"
          LDFLAGS: "${{matrix.ldflags}}" # LLVM_LDFLAGS & MPI_LIB, but get_hypre_version needs -lc++ path
        with:
          os: ${{runner.os}}
          target: opt
          mpi: ${{matrix.mpi}}
          build-system: make
          hypre-dir: ${{env.HYPRE_TOP_DIR}}
          metis-dir: ${{env.METIS_TOP_DIR}}
          mfem-dir: mfem
          library-only: true  # false
          config-options: CXX=${{env.CXX}} MPICXX=${{env.MPICXX}}

      - name: MFEM Info
        working-directory: mfem
        run: make info

      - name: MFEM Check
        working-directory: mfem
        run: make check

      - name: MFEM Examples
        working-directory: mfem/examples
        run: make test

      - name: MFEM Miniapps
        working-directory: mfem
        run: make test-miniapps

      - name: MFEM Unittest
        working-directory: mfem
        run: make unittest
